-- De drie werklijsten als startpunt
--
-- Negen papieren lijsten worden er drie: openen, voorbereiden, sluiten.
-- De weeklijst met dieptaken wordt geen vierde lijst maar een ritme; die taken
-- verschijnen onderaan de sluitlijst op de dag dat ze aan de beurt zijn.
--
-- Overgenomen uit de werklijsten in iCloud. Dit is een startpunt: Sander past ze
-- aan in het beheerscherm. Niets hiervan staat in de code.

ALTER TABLE public.haccp_taken
  ADD COLUMN IF NOT EXISTS lijst       text,
  ADD COLUMN IF NOT EXISTS hoek        text,
  ADD COLUMN IF NOT EXISTS toelichting text,
  ADD COLUMN IF NOT EXISTS ritme       text NOT NULL DEFAULT 'dagelijks',
  -- leeg = elke dag. Anders 0=zondag t/m 6=zaterdag.
  ADD COLUMN IF NOT EXISTS dagen       smallint[];

ALTER TABLE public.haccp_taken DROP CONSTRAINT IF EXISTS haccp_taken_lijst_check;
ALTER TABLE public.haccp_taken ADD CONSTRAINT haccp_taken_lijst_check
  CHECK (lijst IS NULL OR lijst IN ('openen', 'voorbereiden', 'sluiten'));

ALTER TABLE public.haccp_taken DROP CONSTRAINT IF EXISTS haccp_taken_ritme_check;
ALTER TABLE public.haccp_taken ADD CONSTRAINT haccp_taken_ritme_check
  CHECK (ritme IN ('dagelijks', 'wekelijks'));

-- Alleen invoeren als er nog geen werklijsten staan, zodat deze migratie geen
-- eigen aanpassingen van Sander overschrijft als hij nog eens draait.
INSERT INTO public.haccp_taken (lijst, hoek, naam, toelichting, ritme, volgorde, type, actief)
SELECT v.lijst, v.hoek, v.naam, v.toelichting, v.ritme, v.volgorde,
       CASE v.lijst WHEN 'sluiten' THEN 'sluiting' ELSE 'opening' END, true
FROM (VALUES
  ('openen', 'keuken', 'Temperatuur koeling en vries controleren', 'opent het meetscherm', 'dagelijks', 10),
  ('openen', 'keuken', 'Gas en afzuiging aanzetten', NULL, 'dagelijks', 20),
  ('openen', 'keuken', 'Bakplaten aanzetten', 'grote aan, de andere als reserve', 'dagelijks', 30),
  ('openen', 'keuken', 'Oven aanzetten', NULL, 'dagelijks', 40),
  ('openen', 'keuken', 'Vaatwasser aanzetten', NULL, 'dagelijks', 50),
  ('openen', 'keuken', 'Werkbanken schoon en klaar', NULL, 'dagelijks', 60),
  ('openen', 'keuken', 'Snijplanken en gereedschap klaar', NULL, 'dagelijks', 70),
  ('openen', 'keuken', 'Mise en place uit koeling en klaarzetten', NULL, 'dagelijks', 80),
  ('openen', 'bakwand', 'Bakwand aan', 'om 11:15', 'dagelijks', 90),
  ('openen', 'bakwand', 'Koude bain-marie aan en vullen', 'vanuit vitrinekoeling', 'dagelijks', 100),
  ('openen', 'bakwand', 'Warme bain-marie aan en vullen', 'vanuit vitrinekoeling', 'dagelijks', 110),
  ('openen', 'ijshoek', 'Softijsmachine aan', 'hoeveelheden ijs en siropen controleren', 'dagelijks', 120),
  ('openen', 'koffiehoek', 'Koffie aan', NULL, 'dagelijks', 130),
  ('openen', 'vitrine', 'Coca-Cola koeling aan', NULL, 'dagelijks', 140),
  ('openen', 'vitrine', 'Verlichting vitrine aan', NULL, 'dagelijks', 150),
  ('openen', 'vitrine', 'Snackkoeling onder inpak controleren', NULL, 'dagelijks', 160),
  ('openen', 'kassa', 'Kassa opstarten en wisselgeld', NULL, 'dagelijks', 170),
  ('openen', 'gastgedeelte', 'Toiletten controleren en voorraad', 'zeep, handdoekjes, papier', 'dagelijks', 180),
  ('openen', 'buiten', 'Deur open en bord op ''open''', NULL, 'dagelijks', 190),
  ('openen', 'buiten', 'Vlag buiten hangen', NULL, 'dagelijks', 200),
  ('openen', 'buiten', 'Terras rechtzetten', NULL, 'dagelijks', 210),
  ('voorbereiden', 'bakwand', 'Extra frituurpan op tijd opwarmen', 'ca. 45 minuten, preventief starten', 'dagelijks', 220),
  ('voorbereiden', 'bakwand', 'Bakwand volledig gevuld', 'zakjes, bakjes, bordjes, mosterd, loempiasaus', 'dagelijks', 230),
  ('voorbereiden', 'bakwand', 'Warme bain-marie vol', 'pindasaus geroerd en op dikte, backup in keuken, gehaktballen controleren', 'dagelijks', 240),
  ('voorbereiden', 'bakwand', 'Voldoende snacks', 'snackkoeling inpak en vitrine aanvullen', 'dagelijks', 250),
  ('voorbereiden', 'bakwand', 'Voldoende patat klaar', 'op karretje in keuken, minimaal 6 doos', 'dagelijks', 260),
  ('voorbereiden', 'bakwand', 'Frituurvet op peil', NULL, 'dagelijks', 270),
  ('voorbereiden', 'vitrine', 'Vitrine volledig gevuld', NULL, 'dagelijks', 280),
  ('voorbereiden', 'vitrine', 'Frisdrankvitrine vol', NULL, 'dagelijks', 290),
  ('voorbereiden', 'vitrine', 'Snackkoeling inpak vol', NULL, 'dagelijks', 300),
  ('voorbereiden', 'vitrine', 'Sauzen bijgevuld', 'bakwand en vitrine', 'dagelijks', 310),
  ('voorbereiden', 'vitrine', 'Milkshake- en sundaesiropen vol', NULL, 'dagelijks', 320),
  ('voorbereiden', 'vitrine', 'Softijsvoorraad in koelcel', NULL, 'dagelijks', 330),
  ('voorbereiden', 'vitrine', 'Voldoende ijswafels', NULL, 'dagelijks', 340),
  ('voorbereiden', 'vitrine', 'Voldoende portiebakjes, verpakkingen en tasjes', NULL, 'dagelijks', 350),
  ('voorbereiden', 'keuken', 'Mise en place compleet', NULL, 'dagelijks', 360),
  ('voorbereiden', 'keuken', 'Extra voorraad klaar voor de spits', NULL, 'dagelijks', 370),
  ('voorbereiden', 'keuken', 'Werkbanken tussendoor schoonhouden', NULL, 'dagelijks', 380),
  ('voorbereiden', 'keuken', 'Bakplaten tussendoor schoon', NULL, 'dagelijks', 390),
  ('voorbereiden', 'keuken', 'Mise en place bijvullen', NULL, 'dagelijks', 400),
  ('voorbereiden', 'keuken', 'Afval legen indien vol', NULL, 'dagelijks', 410),
  ('voorbereiden', 'keuken', 'Vloer bijhouden', NULL, 'dagelijks', 420),
  ('voorbereiden', 'kassa', 'Wisselgeld en kassa klaar', NULL, 'dagelijks', 430),
  ('voorbereiden', 'kassa', 'Bestelsite en afhaal gecontroleerd', NULL, 'dagelijks', 440),
  ('sluiten', 'bakwand', 'Restproducten eruit', NULL, 'dagelijks', 450),
  ('sluiten', 'bakwand', 'Warme bain-marie leeg', 'linkervak vitrine', 'dagelijks', 460),
  ('sluiten', 'bakwand', 'Koude bain-marie leeg', 'rechtervak vitrine', 'dagelijks', 470),
  ('sluiten', 'bakwand', 'Patat in middenvak vitrine', NULL, 'dagelijks', 480),
  ('sluiten', 'bakwand', 'Beide bain-maries uit en schoon', NULL, 'dagelijks', 490),
  ('sluiten', 'bakwand', 'Ras in de koeling in de keuken en schoonmaken', NULL, 'dagelijks', 500),
  ('sluiten', 'bakwand', 'Bakwand schoonmaken, alle lagen', 'ook onderkant en bovenkant, op zondag in de olie', 'dagelijks', 510),
  ('sluiten', 'bakwand', 'Stangetjes boven de pannen schoon', NULL, 'dagelijks', 520),
  ('sluiten', 'bakwand', 'Sauspompen schoon', 'met alcohol', 'dagelijks', 530),
  ('sluiten', 'bakwand', 'Filters frituurpannen schoonmaken', 'snack, patat, spitspatat', 'dagelijks', 540),
  ('sluiten', 'bakwand', 'Frituurpannen uit', NULL, 'dagelijks', 550),
  ('sluiten', 'ijshoek', 'Softijsmachine schoon', 'bovenkant met doekje', 'dagelijks', 560),
  ('sluiten', 'ijshoek', 'Uitloop schoonmaken en met alcohol', NULL, 'dagelijks', 570),
  ('sluiten', 'ijshoek', 'Lekbak in de vaatwasser', 'schoon bovenop de machine', 'dagelijks', 580),
  ('sluiten', 'ijshoek', 'Voorraad bijvullen voor volgende dag', 'ijs, siropen', 'dagelijks', 590),
  ('sluiten', 'ijshoek', 'Bekers, deksels en rietjes bijvullen', NULL, 'dagelijks', 600),
  ('sluiten', 'ijshoek', 'IJswafels in bak bij elkaar en dicht doen', NULL, 'dagelijks', 610),
  ('sluiten', 'ijshoek', 'Sundaesiropen netjes en afgesloten', NULL, 'dagelijks', 620),
  ('sluiten', 'ijshoek', 'Toppings in grote bak, kleine opvangbakjes leeg', 'eventueel schoonmaken', 'dagelijks', 630),
  ('sluiten', 'ijshoek', 'Werkblad en oppervlakken ijshoek afnemen', NULL, 'dagelijks', 640),
  ('sluiten', 'ijshoek', 'Softijsmachine op standby of pasteuriseren', NULL, 'dagelijks', 650),
  ('sluiten', 'koffiehoek', 'Koffiemachine schoon', 'spoelprogramma of reiniging', 'dagelijks', 660),
  ('sluiten', 'koffiehoek', 'Uitloop en tuitjes schoonmaken', NULL, 'dagelijks', 670),
  ('sluiten', 'koffiehoek', 'Lekbak en opvangbakjes legen en schoon', NULL, 'dagelijks', 680),
  ('sluiten', 'koffiehoek', 'Melkreservoir en -slang legen en schoon', NULL, 'dagelijks', 690),
  ('sluiten', 'koffiehoek', 'Bonen bijvullen voor volgende dag', NULL, 'dagelijks', 700),
  ('sluiten', 'koffiehoek', 'Werkblad koffiehoek afnemen', NULL, 'dagelijks', 710),
  ('sluiten', 'koffiehoek', 'Koffiemachine uit', NULL, 'dagelijks', 720),
  ('sluiten', 'vitrine', 'Snacks voor het nazitten eruit halen', NULL, 'dagelijks', 730),
  ('sluiten', 'vitrine', 'Bijvullen zo nodig', NULL, 'dagelijks', 740),
  ('sluiten', 'vitrine', 'Schalen luchtdicht afdekken met folie', NULL, 'dagelijks', 750),
  ('sluiten', 'vitrine', 'Vitrine afdekken met noppenfolie', NULL, 'dagelijks', 760),
  ('sluiten', 'vitrine', 'Snackkoeling onder inpakbalie netjes en bijvullen', 'voor volgende dag', 'dagelijks', 770),
  ('sluiten', 'vitrine', 'Tasjes inpakbalie aanvullen', NULL, 'dagelijks', 780),
  ('sluiten', 'vitrine', 'Werkblad inpakbalie afnemen', NULL, 'dagelijks', 790),
  ('sluiten', 'vitrine', 'Doekje over glaswerk en vitrinebalie', NULL, 'dagelijks', 800),
  ('sluiten', 'vitrine', 'Kassahoek schoonmaken', NULL, 'dagelijks', 810),
  ('sluiten', 'vitrine', 'Doekje over beeldscherm', NULL, 'dagelijks', 820),
  ('sluiten', 'vitrine', 'Fooi verdelen', NULL, 'dagelijks', 830),
  ('sluiten', 'vitrine', 'Beide afvalbakken legen', NULL, 'dagelijks', 840),
  ('sluiten', 'gastgedeelte', 'Tafels schoon, netjes en aangevuld', 'ook menukaarten en peper- en zoutstelletjes', 'dagelijks', 850),
  ('sluiten', 'gastgedeelte', 'Grote vuilnisbak bij de ingang legen indien vol', NULL, 'dagelijks', 860),
  ('sluiten', 'gastgedeelte', 'Gastengedeelte vegen', 'wo, vr en zo stofzuigen in plaats van vegen', 'dagelijks', 870),
  ('sluiten', 'gastgedeelte', 'Toiletten schoonmaken', 'altijd met spray, zondag met sop, prullenbakken legen en bijvullen', 'dagelijks', 880),
  ('sluiten', 'gastgedeelte', 'Gastengedeelte dweilen', NULL, 'dagelijks', 890),
  ('sluiten', 'keuken', 'Gasfornuis schoon', NULL, 'dagelijks', 900),
  ('sluiten', 'keuken', 'Bakplaten schoon', 'eronder en tussenstukje', 'dagelijks', 910),
  ('sluiten', 'keuken', 'Oven schoon', NULL, 'dagelijks', 920),
  ('sluiten', 'keuken', 'Magnetron schoon', NULL, 'dagelijks', 930),
  ('sluiten', 'keuken', 'Vaatwasser leegmaken en filter checken', 'af en toe grondig reinigen', 'dagelijks', 940),
  ('sluiten', 'keuken', 'Werkbanken schoon', NULL, 'dagelijks', 950),
  ('sluiten', 'keuken', 'Tegeltjes schoon', NULL, 'dagelijks', 960),
  ('sluiten', 'keuken', 'Muur en onderkant plank schoon', NULL, 'dagelijks', 970),
  ('sluiten', 'keuken', 'Saladieren afgedekt of in koeling', NULL, 'dagelijks', 980),
  ('sluiten', 'keuken', 'Koelkast netjes', NULL, 'dagelijks', 990),
  ('sluiten', 'keuken', 'Datumstickers checken', NULL, 'dagelijks', 1000),
  ('sluiten', 'keuken', 'Afval weg, vaatwerk opgeruimd', NULL, 'dagelijks', 1010),
  ('sluiten', 'keuken', 'Vloer vegen en dweilen', NULL, 'dagelijks', 1020),
  ('sluiten', 'keuken', 'Gasfornuis uit', NULL, 'dagelijks', 1030),
  ('sluiten', 'keuken', 'Bakplaten uit', NULL, 'dagelijks', 1040),
  ('sluiten', 'keuken', 'Oven uit', NULL, 'dagelijks', 1050),
  ('sluiten', 'keuken', 'Vaatwasser uit', NULL, 'dagelijks', 1060),
  ('sluiten', 'keuken', 'Afzuiging uit', NULL, 'dagelijks', 1070),
  ('sluiten', 'afsluiten', 'Kassa afsluiten', 'controleer dit blok - overgenomen uit de uitleg, niet uit een lijst', 'dagelijks', 1080),
  ('sluiten', 'afsluiten', 'Alarm aan', 'controleer dit blok - overgenomen uit de uitleg, niet uit een lijst', 'dagelijks', 1090),
  ('sluiten', 'afsluiten', 'Deuren op slot', 'controleer dit blok - overgenomen uit de uitleg, niet uit een lijst', 'dagelijks', 1100),
  ('sluiten', 'keuken', 'Schappen koel- en vriescel leeg en schoon', NULL, 'wekelijks', 1110),
  ('sluiten', 'keuken', 'Vloer koel- en vriescel dweilen', NULL, 'wekelijks', 1120),
  ('sluiten', 'keuken', 'Alle planken leeg en schoon', 'ook onderkant', 'wekelijks', 1130),
  ('sluiten', 'keuken', 'Koeling keuken leeg en schoon', NULL, 'wekelijks', 1140),
  ('sluiten', 'keuken', 'Alle apparaten buitenom schoon', NULL, 'wekelijks', 1150),
  ('sluiten', 'keuken', 'Onderkant keuken leeg en schoon', 'ook onder de wasbak', 'wekelijks', 1160),
  ('sluiten', 'bakwand', 'Bakwand helemaal leeg en schoon', NULL, 'wekelijks', 1170),
  ('sluiten', 'bakwand', 'Koeling bakwand leeg en schoon', NULL, 'wekelijks', 1180),
  ('sluiten', 'vitrine', 'Tasjeshoek leeg en schoon', NULL, 'wekelijks', 1190),
  ('sluiten', 'vitrine', 'Vitrine leeg en schoon, glas poetsen', NULL, 'wekelijks', 1200),
  ('sluiten', 'vitrine', 'Koeling balie leeg en schoon', NULL, 'wekelijks', 1210),
  ('sluiten', 'vitrine', 'IJshoek alles van de kant en schoon', NULL, 'wekelijks', 1220),
  ('sluiten', 'vitrine', 'Plank boven kassa leeg en schoon', NULL, 'wekelijks', 1230),
  ('sluiten', 'vitrine', 'Glazenkast leeg en schoon', NULL, 'wekelijks', 1240),
  ('sluiten', 'gastgedeelte', 'Stoelpoten en tafelpoten', NULL, 'wekelijks', 1250),
  ('sluiten', 'gastgedeelte', 'Wc met sop en tegels', NULL, 'wekelijks', 1260)
) AS v(lijst, hoek, naam, toelichting, ritme, volgorde)
WHERE NOT EXISTS (SELECT 1 FROM public.haccp_taken WHERE lijst IS NOT NULL);
